### ISSUE TITLE
Error starting signalk-polar

### ISSUE THREAD

**Issue by znuzein** [joabakk/signalk-polar#76] opened 2022-06-20 22:36 UTC
Hi.
On my Raspberry pi 4 with PiCAN-M I have installed signalk, SQlite3 and signalk-polar. But the signalk-polar does not start.
I get this error:
Failed to start: Invalid argument: got undefined at index 0.

Hoping you can help with this issue.

Regards

Sten

**Comment by joma42** [comment] 2022-07-23 16:06
Hi,
I have the same setup. I can see that something was writen to the SQlite database. Also in SingnaK, Data browser I can see many new sentences coming from signalk-polar but many of them showing zero.

Path					                               Value	Units	Timestamp	Source
environment.wind.angleTrueWater 	               0.541 	rad	        07/23 10:21:53	signalk-polar
environment.wind.speedTrue 		               4.83	        m/s	        07/23 10:21:53	signalk-polar
performance.beatAngle 			                       0.541	rad	        07/23 17:47:41	signalk-polar
performance.beatAngleTargetSpeed 	               0	        m/s	        07/23 17:47:41	signalk-polar
performance.beatAngleVelocityMadeGood 	       0.5410	m/s	        07/23 17:47:41	signalk-polar
performance.gybeAngle 			               0.01739	rad	        07/23 17:47:41	signalk-polar
performance.gybeAngleTargetSpeed 	               0	        m/s	        07/23 17:47:41	signalk-polar
performance.gybeAngleVelocityMadeGood 	       0	        m/s	        07/23 17:47:41	signalk-polar
performance.polarSpeed 			               null	        m/s	        07/23 17:47:41	signalk-polar
performance.polarSpeedRatio 		               null	        ratio	07/23 17:47:42	signalk-polar
performance.targetAngle 		                       0.54105	rad	        07/23 17:47:41	signalk-polar
performance.targetSpeed 		                      0	        m/s	        07/23 17:47:41	signalk-polar
performance.velocityMadeGood 		              0	        m/s	        07/23 10:21:53	signalk-polar

I guess the problem is that some of the input data sets have different names. Also, sometimes I have two or more sources with the same date. This is because the system is old and I am currently running the old system and a new system in parallel.

It would be very helpful to know what the requirements are and how I can make changes. I am not a programmer.

**Comment by joabakk** [comment] 2022-09-16 19:39
I have published a new version since this issue, so I am closing this issue here. Feel free to open a new one or reopen this if the exact same happens

**Closed as completed by joabakk** 2022-09-16 19:39 UTC

**Comment by znuzein** [comment] 2022-09-17 16:55
👍
